language: node_js

node_js:
  - "0.10"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0a43ba3884562555a9c1
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true     # default: false